stages:
 - build
 - test
 - deploy

build-job:
 stage: build
 script:
    - echo "Compiling the code..."
    - echo "Compile complete."

image: ruby:3.1
before_script:
 - apt-get update -qq && apt-get install -y nodejs npm
 - npm install -g jest
 - npm install

unit-test-job:
 stage: test
 script:
    - echo "Running unit tests with Jest..."
    - jest --coverage
    - echo "Code coverage is above 90%"

lint-test-job:
 stage: test
 script:
    - echo "Linting code... This will take about 10 seconds."
    - npm run lint
    - echo "No lint issues found."

deploy-job:
 stage: deploy
 environment: production
 script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
