import type { Metadata } from "next";
import { Inter, Josefin_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Provider } from "react-redux";
import { store } from "../redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets:['latin'],
  weight:["400", "500", "600", "700"],
  variable:"--font-Poppins"
})

const josefin = Josefin_Sans({
  subsets:['latin'],
  weight:["400", "500", "600", "700"],
  variable:"--font-Josefin"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}
          <div className={ `${poppins.variable} ${josefin.variable}`}>
            {children}
            <Toaster position="top-center" reverseOrder={false}/>
          </div>
        {/* </Provider> */}
      </body>
    </html>
  );
}
